FROM python:3.11-slim

# build-essential is required to build a wheel for ciso8601
RUN apt update && apt install -y build-essential

RUN python -m pip install --upgrade pip
RUN python -m pip install "numpy<2" mkdocs mkdocs-material pdocs pystac

COPY . /opt/src

WORKDIR /opt/src

RUN python -m pip install .

CMD ["pdocs", \
    "as_markdown", \
    "--output_dir", \
    "docs/api/", \
    "--exclude_source", \
    "--overwrite", \
    "stac_fastapi.sqlalchemy"]
